export const DEFAULT_PANTRY_STAPLES = [
  "Olive oil",
  "Vegetable oil",
  "Butter",
  "Salt",
  "Black pepper",
  "Garlic",
  "Onions",
  "Soy sauce",
  "Chicken stock cubes",
  "Plain flour",
  "Rice",
  "Pasta (spaghetti/penne)",
  "Canned tomatoes",
  "Tomato paste",
  "Sugar",
  "Honey",
  "Vinegar (white/red wine)",
  "Mustard",
  "Eggs",
  "Milk",
  "Parmesan cheese",
  "Dried herbs (oregano, thyme, rosemary)",
  "Paprika",
  "Cumin",
  "Chilli flakes",
  "Cornflour",
  "Bread",
  "Lemons",
];
